export const DEFAULT_EXERCISES: Readonly<Set<string>> = Object.freeze(
  new Set([
    'Back Squat',
    'Front Squat',
    'Overhead Squat',
    'Box Squat',
    'Goblet Squat',
    'Zercher Squat',
    'Hack Squat',
    'Bulgarian Split Squat',
    'Split Squat',
    'Walking Lunge',
    'Reverse Lunge',
    'Step-Up',
    'Leg Press',
    'Sumo Squat',
    'Smith Machine Squat',
    'Single-Leg Press',
    'Romanian Deadlift',
    'Stiff-Leg Deadlift',
    'Conventional Deadlift',
    'Sumo Deadlift',
    'Trap Bar Deadlift',
    'Deficit Deadlift',
    'Snatch-Grip Deadlift',
    'Rack Pull',
    'Good Morning',
    'Glute Bridge',
    'Hip Thrust',
    'Single-Leg Romanian Deadlift',
    'Kettlebell Swing',
    'Kettlebell Deadlift',
    'Hip Hinge',
    'Back Extension',
    'Glute-Ham Raise',
    'Cable Pull-Through',
    'Leg Curl (Lying)',
    'Leg Curl (Seated)',
    'Nordic Hamstring Curl',
    'Leg Extension',
    'Standing Calf Raise',
    'Seated Calf Raise',
    'Donkey Calf Raise',
    'Tibialis Raise',
    'Barbell Bench Press (Flat)',
    'Barbell Bench Press (Incline)',
    'Barbell Bench Press (Decline)',
    'Dumbbell Bench Press',
    'Dumbbell Incline Press',
    'Dumbbell Decline Press',
    'Close-Grip Bench Press',
    'Floor Press',
    'Pin Press',
    'Swiss Bar Bench Press',
    'Smith Machine Bench Press',
    'Chest Press Machine',
    'Pec Deck Fly',
    'Cable Crossover',
    'Dumbbell Fly',
    'Single-Arm Cable Fly',
    'Push-Up (Standard)',
    'Push-Up (Decline)',
    'Push-Up (Incline)',
    'Weighted Push-Up',
    'Incline Push-Up',
    'Dips (Parallel Bars)',
    'Bench Dip',
    'Weighted Dip',
    'Overhead Press (Standing)',
    'Seated Overhead Press',
    'Dumbbell Shoulder Press',
    'Arnold Press',
    'Push Press',
    'Push Jerk',
    'Split Jerk',
    'Military Press',
    'Landmine Press',
    'Single-Arm Landmine Press',
    'Smith Machine Overhead Press',
    'Lateral Raise (Dumbbell)',
    'Front Raise (Dumbbell)',
    'Reverse Fly (Dumbbell)',
    'Rear Delt Fly (Cable)',
    'Face Pull',
    'Upright Row',
    'Shrug (Barbell)',
    'Shrug (Dumbbell)',
    'Farmer Carry',
    'Suitcase Carry',
    'Overhead Carry',
    'Yoke Carry',
    'Sandbag Carry',
    'Plate Carry',
    'T-Bar Row',
    'Bent-Over Barbell Row',
    'Pendlay Row',
    'One-Arm Dumbbell Row',
    'Chest-Supported Row',
    'Seal Row',
    'Meadows Row',
    'Inverted Row',
    'Seated Cable Row',
    'Machine Row',
    'Wide-Grip Row',
    'Single-Arm Cable Row',
    'Lat Pulldown (Wide)',
    'Lat Pulldown (Close)',
    'Straight-Arm Pulldown',
    'Pull-Up (Wide)',
    'Pull-Up (Chin-Up)',
    'Chin-Up',
    'Neutral-Grip Pull-Up',
    'Assisted Pull-Up',
    'Weighted Pull-Up',
    'Cable Lat Row',
    'Machine Pulldown',
    'Reverse-Grip Lat Pulldown',
    'Close-Grip Pulldown',
    'Cable Face Pull',
    'Band Pull-Apart',
    'High Pull',
    'Snatch',
    'Power Snatch',
    'Hang Snatch',
    'Snatch Balance',
    'Clean',
    'Power Clean',
    'Hang Clean',
    'Clean Pull',
    'Clean and Jerk',
    'Split Clean',
    'Muscle Clean',
    'Jerk',
    'Push Jerk',
    'Power Jerk',
    'Barbell Complexes',
    'Kettlebell Clean',
    'Kettlebell Snatch',
    'Turkish Get-Up',
    'Kettlebell Press',
    'Kettlebell Goblet Squat',
    'Kettlebell Lunge',
    'Kettlebell Row',
    'Kettlebell Farmer Carry',
    'Cable Woodchopper',
    'Cable Anti-Rotation Press (Pallof Press)',
    'Russian Twist (Weighted)',
    'Hanging Leg Raise',
    "Captain's Chair Leg Raise",
    'Ab Wheel Rollout',
    'Plank',
    'Side Plank',
    'Weighted Plank',
    'Dead Bug',
    'Bicycle Crunch',
    'Reverse Crunch',
    'Cable Crunch',
    'Machine Crunch',
    'V-Up',
    'Toe Touch',
    'Windshield Wiper',
    'Medicine Ball Slam',
    'Medicine Ball Throw',
    'Sled Push',
    'Sled Pull',
    'Prowler Push',
    'Battle Ropes',
    'Box Jump',
    'Broad Jump',
    'Step Plyo',
    'Power Step-Up',
    'Calisthenics Row',
    'Muscle-Up',
    'Ring Dip',
    'Bar Muscle-Up',
    'Handstand Push-Up',
    'Single-Arm Dumbbell Press',
    'Incline Hammer Curl',
    'Barbell Curl',
    'EZ-Bar Curl',
    'Dumbbell Curl',
    'Concentration Curl',
    'Preacher Curl',
    'Cable Curl',
    'Zottman Curl',
    'Hammer Curl',
    'Reverse Curl',
    'Spider Curl',
    'Incline Dumbbell Curl',
    'Drag Curl',
    'Wrist Curl',
    'Reverse Wrist Curl',
    "Farmer's Walk Holds",
    'Plate Pinch',
    'Grip Crush',
    'Triceps Pushdown (Cable)',
    'Rope Triceps Pushdown',
    'Overhead Triceps Extension (Dumbbell)',
    'Overhead Triceps Extension (Cable)',
    'Skull Crusher (Lying Triceps Extension)',
    'Kickback (Dumbbell)',
    'Single-Arm Cable Kickback',
    'Close-Grip Push-Up',
    'Cable Single-Arm Extension',
    'Triceps Dip Machine',
    'Barbell Pullover',
    'Dumbbell Pullover',
    'Svend Press',
    'Iso Lateral Chest Press',
    'Iso Lateral Row',
    'Horizontal Leg Press',
    'Vertical Leg Press',
    'Machine Hip Abduction',
    'Machine Hip Adduction',
    'Clamshell (with Band)',
    'Banded Lateral Walk',
    'Glute Kickback (Cable)',
    'Cable Hip Abduction',
    'Cable Hip Extension',
    'Ankle Weights Leg Raise',
    'Stair Climber Step',
    'Reverse Hyperextension',
    'Jefferson Squat',
    'Safety Bar Squat',
    'Anderson Squat',
    'Tempo Squat',
    'Paused Squat',
    'Pause Deadlift',
    'Chain-Loaded Bench Press',
    'Band-Loaded Bench Press',
    'Cluster Sets (exercise variant)',
    'Zercher Carry',
    'Bottoms-Up Carry',
    'Kettlebell Snatch to Overhead',
    'Kettlebell Windmill',
    'Kettlebell Turkish Sit-Up',
    'Sled Row',
    'Landmine Row',
    'Incline Row',
    'Decline Row',
    'Single-Leg Hip Thrust',
    'Banded Good Morning',
    'Seated Good Morning',
    'Cable Lateral Raise',
    'Dumbbell External Rotation',
    'Cable Internal Rotation',
    'Cable External Rotation',
    'Bench Supported Rear Delt Row',
    'Pec Minor Stretch Press',
    'Weighted Glute Bridge',
    'Heel-Elevated Squat',
    'Jefferson Deadlift',
    'Sumo Deadlift High Pull',
    'Bodyweight Squat',
    'Prisoner Squat',
    'Hack Deadlift',
    'Axle Bar Deadlift',
    'Fat Bar Carry',
    'Grip Roller',
    'Wrist Roller',
    'Finger Curls',
    'Climbing Pulls',
    'Assisted Dip Machine',
    'Iso-Hold Rows',
    'Overhead Squat Hold',
    'Sots Press',
    'Kettlebell Farmer Clean',
    'Kettlebell Farmer Squat',
    'Reverse-Grip Bench Press',
    'Wide-Grip Bench Press',
    'Narrow-Grip Bench Pres',
  ]),
);
